# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 05:48
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20161004_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusercompany',
            name='doc',
            field=models.FileField(upload_to='', verbose_name=django.core.files.storage.FileSystemStorage()),
        ),
    ]
