# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:29
from __future__ import unicode_literals

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20161005_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusercompany',
            name='doc',
            field=models.FileField(storage=client.models.for_id, upload_to=''),
        ),
    ]
