# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 21:08
from __future__ import unicode_literals

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20161005_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusercompany',
            name='attrribuzione_pi',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientusercompany',
            name='cf_doc',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientusercompany',
            name='doc',
            field=models.FileField(default=None, upload_to=client.models.for_id),
        ),
    ]
