# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20161005_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusercompany',
            name='data_mod',
            field=models.DateTimeField(auto_now_add=True,verbose_name='Data ultima modifica'),
            preserve_default=False,
        ),
    ]
