# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20161017_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientusercompany',
            name='doc',
        ),
    ]
