# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_remove_clientusercompany_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, upload_to='')),
                ('userFile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='File_document', to='client.ClientUserCompany')),
            ],
        ),
    ]
