# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20161017_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='userFile',
        ),
        migrations.AddField(
            model_name='clientusercompany',
            name='prova',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_prova', to='client.documentFile'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
