# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20161018_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientusercompany',
            name='prova',
        ),
    ]
