# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 15:48
from __future__ import unicode_literals

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_remove_clientusercompany_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusercompany',
            name='attrribuzione_pi',
            field=models.FileField(blank=True, storage=client.models.CreateFolderUser(location='/media/'), upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='clientusercompany',
            name='doc',
            field=models.FileField(blank=True, storage=client.models.CreateFolderUser(location='/media/'), upload_to='/media/'),
        ),
    ]
