# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20161018_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusercompany',
            name='data_ins',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inserimento'),
        ),
        migrations.AlterField(
            model_name='clientusercompany',
            name='data_mod',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica'),
        ),
    ]
