# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_auto_20161019_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientusercompany',
            options={'permissions': (('Can_View', 'Può Visualizzare i Clienti'), ('Can_Password', 'Può Modificare la Password'))},
        ),
    ]
