# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 18:35
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_auto_20161026_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusercompany',
            name='spese',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Avvio Attività'), ('2', 'Attrezzature e Macchinari'), ('3', 'Opere Edili e Impianti(Costruzione'), ('4', 'Opere Edili e Impianti(Ristrutturazione)'), ('5', 'Opere Edili e Impianti(Ampliamento)'), ('6', 'Cosulenze/Servizi'), ('7', 'Acquisto Terreno'), ('8', 'Innovazione Ricerca e Sviluppo'), ('9', 'Risparmio Energetico/Fonti Rinnovabili'), ('10', 'Promozione/Export'), ('11', 'Realizzazione Sito Web'), ('12', 'Altro')], max_length=26),
        ),
    ]
