# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_auto_20161028_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientusercompany',
            options={'permissions': (('Can_View', 'Può Visualizzare i Clienti'), ('Can_Password', 'Può Modificare la Password'), ('Can_Down', 'Può Scaticare allegati'), ('Can_View_att', 'Può Visualizzare allegati'))},
        ),
    ]
