# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_auto_20170211_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusercompany',
            name='codice_ateco',
            field=models.CharField(default='', max_length=150, verbose_name='Codice Ateco'),
        ),
        migrations.AlterField(
            model_name='clientusercompany',
            name='numero_rea',
            field=models.CharField(default='', max_length=150, verbose_name='Numero Rea'),
        ),
    ]
