# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_auto_20170215_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusercompany',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Pratica Comletata'),
        ),
    ]
