# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=150, verbose_name='Denominazione')),
                ('indirizzo', models.CharField(max_length=250, verbose_name='Indirizzo')),
                ('numeroCivico', models.PositiveIntegerField(verbose_name='Numero Civico')),
                ('città', models.CharField(default='', max_length=150, verbose_name='Città')),
                ('comune', models.CharField(max_length=100, verbose_name='Comune')),
                ('cap', models.PositiveSmallIntegerField(verbose_name='C.a.p.')),
                ('piva', models.CharField(max_length=14, verbose_name='P.iva')),
                ('cf', models.CharField(max_length=15, verbose_name='Codice Fiscale')),
                ('TelefonoFisso', models.CharField(max_length=15, null=True, verbose_name='Telfono')),
                ('Cellulare', models.CharField(max_length=15, verbose_name='Celluare')),
                ('Fax', models.CharField(max_length=15, verbose_name='Fax')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
            ],
        ),
    ]
