# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0003_auto_20160926_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cellulare',
            new_name='cellulare1',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='telefonoFisso',
            new_name='telefonoFisso1',
        ),
        migrations.AddField(
            model_name='company',
            name='cellulare2',
            field=models.CharField(default=1, max_length=15, verbose_name='Celluare Altro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='telefonoFisso2',
            field=models.CharField(max_length=15, null=True, verbose_name='Telfono Altro'),
        ),
    ]
