# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0004_auto_20160926_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='numeroCivico',
        ),
        migrations.AddField(
            model_name='company',
            name='url_sito',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
