# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0005_auto_20160926_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='data_ins',
            field=models.DateTimeField(auto_now=True, verbose_name='Data inserimento'),
        ),
    ]
