# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0006_company_data_ins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='città',
            new_name='citta',
        ),
    ]
