# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0007_auto_20160926_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='citta',
            field=models.CharField(max_length=150, verbose_name='Città'),
        ),
    ]
