# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0008_auto_20160926_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('Can_View', 'Può Visualizzare la Lista'),)},
        ),
    ]
