# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20161022_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions_set', to='auth.Permission', verbose_name='Permessi Utente'),
        ),
    ]
