# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20161024_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('Can_View', 'Può Visualizzare la Lista'), ('Can_Password', 'Può Modificare la Password'))},
        ),
    ]
